theme: jekyll-theme-merlot
baseurl: http://taqtiqa.github.io
title: [TAQTIQA's Developer Pages]
description: [Opensource tools and projects.]

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

google_analytics: [UA-30030414-2]

exclude: ['README.md']